### PR TITLE
Sync Testing 1.1. -> Stable 1.11

### PR DESCRIPTION
**Pull request by uilianries**

### CODE REVIEW

**Comment by Croydon** [comment]
The testing branch is currently broken, so why this planned merge?

**Comment by uilianries** [comment]
Actually, both stable and testing are broken :cry: 

https://github.com/bincrafters/community/issues/1114

I can check it

**Comment by uilianries** [comment]
I see, you need the `premake/5.0.0-alpha14`, but it's still under review at the ICC. Let me try to push you.

**Comment by Croydon** [comment]
Don't mind `testing/` for now, please. I pretty much "broke that on purpose" or something like that

**Comment by uilianries** [comment]
I see, so your suggestion is fixing stable only?

**Comment by Croydon** [comment]
@uilianries  Yes, exactly 

If you could review https://github.com/conan-io/conan-center-index/pull/647 to push it forward that would still be helpful 😄

**Review by Croydon — APPROVED** [review]

**Pull request merged**
